version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: gnx-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gnx
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gnx-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: gnx-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gnx.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - gnx-network

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  gnx-network:
    driver: bridge
